baseURL = "https://mpcsec.org/"
title = "Common MPC Pitfalls"
languageCode = "en-us"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT", "404"]

[outputs]
home = ["HTML", "llms"]
page = []
section = []

[outputFormats.llms]
mediaType = "text/plain"
baseName = "llms"
isPlainText = true

[markup.highlight]
lineNos = true
lineNumbersInTable = false

[markup.goldmark.parser]
autoHeadingID = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$']]
inline = [['$', '$']]

[[params.contributors]]
name = "Mathias Hall-Andersen"
handle = "rot256"
affiliation = "zkSecurity"

[[params.contributors]]
name = "Mike Junior Sinsoillier"
handle = "jmnis"
affiliation = "zkSecurity"

[[params.contributors]]
name = "Martin Ochoa"
handle = "martin-ochoa"
affiliation = "zkSecurity"
